### Test out some basic functions in Numpy 

In [0]:
#load the library and check its version
import numpy as np
np.__version__

'1.17.4'

In [0]:
#create a list with numbers from 0 to 9
L=list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [0]:
#converting integers to string
S=[str(s) for s in L]
S

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [0]:
#get the types
[type(l) for l in L]

[int, int, int, int, int, int, int, int, int, int]

In [0]:
[type(s) for s in S]

[str, str, str, str, str, str, str, str, str, str]

### Arrays

##### Creating Array

In [0]:
#creating arrays
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [0]:
np.zeros (10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [0]:
#create a 4 row 5 column matrix
np.ones((4,6),dtype=float)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [0]:
#create a matrix with a predefined value
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [0]:
#create an array with a set sequence
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [0]:
#create an array of even space between the given range of values
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [0]:
#create a 3x3 array with mean 0 and standard deviation 1 in a given dimention
np.random.normal(0,1,(3,3))

array([[-0.89199935,  0.92686686, -1.73501961],
       [ 0.39329297,  1.63667964,  0.09150231],
       [ 0.71017252,  1.0411984 , -1.10711877]])

In [0]:
#create a identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [0]:
#set a random seed
np.random.seed(17)
#one dimension
x1=np.random.randint(10,size=5) 
x1


array([1, 6, 6, 9, 0])

In [0]:
#two dimension
x2=np.random.randint(10, size=(2,3))
x2

array([[6, 4, 7],
       [4, 7, 1]])

In [0]:
#three dimention
x3=np.random.randint(10,size=(3,4,5))
x3

array([[[1, 9, 8, 2, 3],
        [6, 6, 9, 9, 1],
        [5, 1, 0, 5, 6],
        [6, 2, 6, 9, 8]],

       [[3, 2, 1, 9, 8],
        [3, 2, 7, 8, 9],
        [2, 1, 8, 1, 8],
        [0, 4, 5, 4, 4]],

       [[3, 3, 3, 7, 8],
        [5, 1, 9, 4, 9],
        [7, 3, 3, 1, 6],
        [1, 3, 8, 3, 2]]])

In [0]:
print("x3 ndim:",x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:",x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


##### Array Slicing

In [0]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
#get value from start to 4th position
x[:5]

array([0, 1, 2, 3, 4])

In [0]:
#get value from 4th position to then end
x[4:]

array([4, 5, 6, 7, 8, 9])

In [0]:
#get value from 4th to 6th position
x[4:7]

array([4, 5, 6])

In [0]:
#get value at even place
x[::2]

array([0, 2, 4, 6, 8])

In [0]:
#get elements from first position step by two
x[1::2]

array([1, 3, 5, 7, 9])

In [0]:
#reverse the array
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

##### Array Concatenation

In [0]:
#concatenate two or more arrays at once
x=np.array([1,2,3])
y=np.array([4,5,6])
z=[7,7,7]
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 7, 7])

In [0]:
#create 2-dimensional arrays
g=np.array([[1,2,3],[4,5,6]])
np.concatenate([g,g])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [0]:
#define row-wise or column-wise matrix
np.concatenate([g,g],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [0]:
np.concatenate([g,g],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

###### concatenation works for equal dimension arrays. for non equal dimension arrays can use np.vstack np.hstack

In [0]:
x=np.array([1,2,3])
g= np.array([[4,5,6],[7,8,9]])
np.vstack([x,g])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
z=np.array([[10],[10]])
np.hstack([g,z])

array([[ 4,  5,  6, 10],
       [ 7,  8,  9, 10]])

In [0]:
#split arrays based on pre-defined positions
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
x1,x2,x3=np.split(x,[3,6])
print (x1,x2,x3)

[0 1 2] [3 4 5] [6 7 8 9]


In [0]:
g=np.arange(16).reshape((4,4))
g

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [0]:
upper,lower=np.vsplit(g,[2])
print(upper, lower)

[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]
